# Composicao do programa de teste do módulo baralho utilizando o arcabouço

[Diretorios]

Nome        =  BARALHO
PathDefault =  ..\Srcs\BARALHO
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Srcs\BARALHO
h           =  ..\Srcs\BARALHO

[Modulos]
TESTBAR
BARALHO
LISTA

[BuildInicio]
/OUT:..\Produto\TRAB4-2.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]

